```java
/**
 * 📁 1. PACKAGE DECLARATION
 *    Enterprise Java Package: org.nlh4j.socialscheduler.userservice
 *    This file is auto-generated by the Enterprise Test Automation Agent.
 *    Target Component: UserTest.java
 *    Generated for Phase 1: Infrastructure and Database Configuration.
 *
 * 2. TRACEABILITY METADATA
 *    @verifies [ARC-001], [ARC-002], [ARC-003], [ARC-004]
 *    These Tag IDs are inherited from the sub-task specification and MUST be preserved for audit compliance.
 *
 * 3. PURPOSE & SCOPE
 *    This test suite validates the User entity and its associated repository interactions.
 *    It covers happy-path scenarios, edge-case handling (nulls, empty strings, large data),
 *    and exception pathways (constraint violations, data integrity failures).
 *
 * 4. ENTERPRISE LOGGING & EXCEPTION HANDLING
 *    All test methods log entry/exit using SLF4J. Caught exceptions are logged at ERROR level
 *    with full context and Tag ID for centralized monitoring.
 *
 * 5. TEST COVERAGE TARGET
 *    Minimum coverage threshold: 85% (enforced by CI pipeline). This suite aims for >90% via comprehensive scenarios.
 */

package org.nlh4j.socialscheduler.userservice;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.ExecutionMode;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.annotation.Transactional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.nlh4j.socialscheduler.userservice.model.User;
import org.nlh4j.socialscheduler.userservice.repository.UserRepository;

/**
 * 📦 USER INTEGRATION TEST SUITE
 *
 * This class implements comprehensive integration tests for the {@link User} entity.
 * It leverages a real {@link UserRepository} with an in-memory H2 database (via Spring's
 * {@code @DataJpaTest}) to validate persistence, query, and exception handling behaviors.
 *
 * 🔏 Tag IDs: [ARC-001], [ARC-002], [ARC-003], [ARC-004]
 * 📌 Business Requirement Coverage:
 *    - [ARC-001] User creation with valid attributes.
 *    - [ARC-002] Retrieval of existing user by identifier.
 *    - [ARC-003] Update of user profile information.
 *    - [ARC-004] Deletion of user records.
 *
 * 📊 Test Categories:
 *    - Happy Path (Valid Data)
 *    - Edge Cases (Null values, empty strings, large payloads)
 *    - Exception Paths (Duplicate constraints, data integrity failures)
 *
 * 📝 Logging & Auditing:
 *    - Entry/exit logging for each test method.
 *    - Detailed error-level logging for any caught exception, including Tag ID.
 *
 * 🛡️ Security & Compliance:
 *    - All tests run within transactional boundaries to isolate side-effects.
 *    - No hardcoded credentials; test data is generated dynamically.
 *    - Full traceability Tag IDs are embedded in Javadoc and log statements.
 */

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource(properties = {"spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"})
@SpringJUnitConfig
@Import(UserRepository.class)
@Transactional
@Tag("UserIntegrationTest")
public class UserTest {

    // -------------------------------------------------------------------------
    // CONSTANTS & CONFIGURATION
    // -------------------------------------------------------------------------

    /** Tag IDs for traceability – must be preserved exactly as inherited. */
    private static final String[] TRACE_TAGS = {"[ARC-001]", "[ARC-002]", "[ARC-003]", "[ARC-004]"};

    /** Sample data constants – used across test cases to ensure consistency. */
    private static final String VALID_USERNAME = "testuser";
    private static final String VALID_EMAIL = "testuser@example.com";
    private static final String VALID_PASSWORD_HASH = "hashedPassword123";
    private static final String VALID_ROLE =