package org.nlh4j.socialscheduler.schedulingservice;

/**
 * Integration Test Suite for ScheduleRepository
 * Validates multi-component database workflow, CRUD operations, and edge-case handling
 * for the Scheduling Service within the social-scheduler enterprise system.
 *
 * @verifies [REQ-001], [EXC-001], [EXC-002]
 * @TestPropertySource(properties = {
 *     "spring.datasource.url=jdbc:postgresql://localhost:5432/social_scheduler",
 *     "spring.datasource.username=sa",
 *     "spring.datasource.password=password",
 *     "spring.jpa.hibernate.ddl-auto=update"
 * })
 */
import org.junit.jupiter.api.*;
import org.springframework.boot.test.context.*;
import org.testcontainers.junit.jupiter.*;
import org.testcontainers.containers.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import java.time.*;

/**
 * Integration test class for ScheduleRepository operations.
 * Bootstraps full runtime infrastructure via Testcontainers PostgreSQL
 * to execute real database queries, CRUD operations, and state validation.
 */
@SpringBootTest
@Testcontainers
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:postgresql://localhost:5432/social_scheduler",
    "spring.datasource.username=sa",
    "spring.datasource.password=password",
    "spring.jpa.hibernate.ddl-auto=update"
})
class ScheduleRepositoryTest {

    /**
     * PostgreSQL container providing a real database instance for integration testing.
     * Default port 5432 aligns with the @TestPropertySource datasource URL configuration.
     */
    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15")
            .withDatabaseName("social_scheduler")
            .withUsername("sa")
            .withPassword("password");

    /**
     * Autowired Spring Data JPA repository under test.
     * All test methods operate on this real database instance.
     */
    @Autowired
    ScheduleRepository scheduleRepository;

    /**
     * [REQ-001] Verifies that a schedule entity can be persisted to the database
     * and subsequently retrieved via its generated ID, ensuring CRUD integrity.
     * Edge-case validation: Confirms non-null ID generation and content/platform preservation.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [REQ-001] Save and retrieve a schedule by ID")
    void testSaveAndFindById_happyPath() {
        // Arrange: Construct a valid Schedule object with required attributes
        Schedule schedule = new Schedule();
        schedule.setPlatform("Facebook");
        schedule.setContent("Test post content for integration validation.");
        schedule.setScheduledTime(LocalDateTime.now().plusHours(1));
        schedule.setStatus("pending");

        // Act: Persist the schedule and capture the generated ID
        Schedule saved = scheduleRepository.save(schedule);

        // Assert: Verify the saved record has a non-null ID assigned by the database
        assertThat(saved.getScheduleId()).isNotNull()
                .as("Schedule ID must be generated by the persistence layer per [REQ-001]");

        // Assert: Retrieve the schedule by ID and validate field fidelity
        Schedule retrieved = scheduleRepository.findById(saved.getScheduleId())
                .orElseThrow(() -> new AssertionError("Schedule should exist in database"));

        // Assertion logic: Content must match exact input string
        assertThat(retrieved.getContent()).isEqualTo("Test post content for integration validation.")
                .as("Persisted content must be faithfully retrieved");

        // Assertion logic: Platform must be preserved exactly as provided
        assertThat(retrieved.getPlatform()).isEqualTo("Facebook")
                .as("Platform tag must survive persistence round-trip");

        // Assertion logic: Default status must be 'pending' as per domain model constraints
        assertThat(retrieved.getStatus()).isEqualTo("pending")
                .as("Initial status must default to pending per business rule");
    }

    /**
     * [EXC-001] Verifies that querying a schedule by a non-existent ID
     * gracefully returns Optional.empty() without throwing unhandled exceptions.
     * Edge-case validation: Ensures database query resilience for missing keys.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [EXC-001] Find schedule by non-existent ID returns empty")
    void testFindById_nonExisting() {
        // Arrange: Generate a UUID that will never match any persisted record
        UUID nonExistentId = UUID.randomUUID();

        // Act: Attempt to find schedule by the non-existent ID
        Optional<Schedule> result = scheduleRepository.findById(nonExistentId);

        // Assertion logic: Result must be empty; no exception should propagate
        assertThat(result).isEmpty()
                .as("Querying non-existent schedule must return empty Optional per [EXC-001]");
    }

    /**
     * [EXC-002] Verifies that findAll() returns an empty collection
     * when no schedule records are present, preventing null pointer issues downstream.
     * Edge-case validation: Confirms collection type safety and empty-state handling.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [EXC-002] Find all schedules returns empty list when no records exist")
    void testFindAll_whenDatabaseEmpty() {
        // Act: Execute findAll on a fresh database schema
        List<Schedule> schedules = scheduleRepository.findAll();

        // Assertion logic: List must be empty, never null
        assertThat(schedules).isEmpty()
                .as("findAll() must return empty collection when no records are present, avoiding NPE");
    }

    /**
     * [REQ-001] Verifies that deleteById successfully removes a schedule
     * from the database, and subsequent findById returns empty.
     * Edge-case validation: Confirms idempotent delete behavior and referential integrity.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [REQ-001] Delete schedule by ID and verify removal")
    void testDeleteById_andVerifyRemoval() {
        // Arrange: Persist a temporary schedule record for deletion testing
        Schedule schedule = new Schedule();
        schedule.setPlatform("Instagram");
        schedule.setContent("Delete me post");
        schedule.setScheduledTime(LocalDateTime.now());
        schedule.setStatus("pending");
        Schedule saved = scheduleRepository.save(schedule);

        // Act: Issue delete operation by the generated ID
        scheduleRepository.deleteById(saved.getScheduleId());

        // Assert: Verify the record is physically removed from the database
        Optional<Schedule> deleted = scheduleRepository.findById(saved.getScheduleId());
        assertThat(deleted).isEmpty()
                .as("Deleted schedule must no longer be retrievable, ensuring data cleanup integrity per [REQ-001]");
    }

    /**
     * [REQ-001] Verifies that the count() method accurately reports
     * the number of schedule records in the database, useful for
     * pagination and capacity planning logic.
     * Edge-case validation: Confirms count accuracy after incremental inserts.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [REQ-001] Count schedules accurately reflects database state")
    void testCount_reflectsState() {
        // Arrange: Capture the initial record count before modifications
        long initialCount = scheduleRepository.count();

        // Act: Save a new schedule record and re-query count
        Schedule s = new Schedule();
        s.setPlatform("Twitter");
        s.setContent("Count test");
        s.setScheduledTime(LocalDateTime.now());
        s.setStatus("pending");
        scheduleRepository.save(s);

        // Assertion logic: Count must increment by exactly one
        assertThat(scheduleRepository.count()).isEqualTo(initialCount + 1)
                .as("Record count must increment accurately after each persist operation per [REQ-001]");
    }

    /**
     * [EXC-002] Verifies existsById returns true for a saved schedule
     * and false for an ID that was never persisted, ensuring robust
     * existence checks before business operations.
     * Edge-case validation: Confirms binary existence semantics for both valid and invalid IDs.
     */
    @Test
    @org.junit.jupiter.api.DisplayName("Test [EXC-002] existsById behavior on valid and invalid IDs")
    void testExistsById_validAndInvalid() {
        // Arrange: Save a schedule record and capture its generated ID
        Schedule s = new Schedule();
        s.setPlatform("LinkedIn");
        s.setContent("Exists test");
        s.setScheduledTime(LocalDateTime.now());
        s.setStatus("pending");
        Schedule saved = scheduleRepository.save(s);
        UUID validId = saved.getScheduleId();

        // Act & Assert: Verify existsById returns true for a persisted ID
        assertThat(scheduleRepository.existsById(validId)).isTrue()
                .as("existsById must return true for a successfully persisted schedule ID");

        // Act & Assert: Verify existsById returns false for a randomly generated invalid ID
        assertThat(scheduleRepository.existsById(UUID.randomUUID())).isFalse()
                .as("existsById must return false for an ID that was never persisted, ensuring safe pre-operation checks per [EXC-002]");
    }
}