# -------------------------------------------------
# GUIDELINE: Due to GitHub not allowing to update secrets by default GITHUB_TOKEN
# -------------------------------------------------
# - Create new TOKEN to grant permission to update secrets:
#   - Settings > Developer settings > Personal Access Tokens > Tokens (classic)
#   - Generate new token > grant token permissions: read/write secrets
#   - Add this token into secrets for checking `PAT_SECRETS_MANAGER`
# -------------------------------------------------

name: 🛡️ GitHub Action Secrets Updater

on:
  # manual trigger workflow
  workflow_dispatch:
    inputs:
      secret_name:
        description: "🔑 Secret Variable Name"
        required: true
        type: string
      secret_value:
        description: "⚙️ Secret Variable Value"
        required: true
        type: string

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read

# enviroment
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

jobs:
  # ==============================================================================
  # 🗑️ Clear history / logs
  # ==============================================================================
  clear-history:
    runs-on: ubuntu-latest
    steps:
      # Check whether allow for running workflow
      - name: 🛡️ Gatekeeper - Validate Administrative Access
        env:
          ALLOW_UPDATE_SECRETS: ${{ secrets.ALLOW_UPDATE_SECRETS }}
        if: ${{ env.ALLOW_UPDATE_SECRETS != 'true' }}
        run: |
          echo "❌ Deployment is administratively DISABLED via GitHub Secrets (secrets.ALLOW_UPDATE_SECRETS is not true)."
          echo "Terminating pipeline execution immediately to protect production infrastructure."
          exit 1 # Require Admin Rights
      
      # Check whether manager token permissions
      - name: 🛡️ Gatekeeper - Validate Manager Token Access
        if: success()                 # if previous step is successful
        env:
          # Use secret PAT to grant permission to update secrets instead of using default GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.PAT_SECRETS_MANAGER }}
          INPUT_NAME: ${{ github.event.inputs.secret_name }}
        run: |
          echo "🛡️ Checking permissions to execute..."
          if ! gh auth status > /dev/null 2>&1; then
            echo "❌ CRITICAL ERROR: Token 'PAT_SECRETS_MANAGER' is INVALID / EXPIRED / NOT EXISTED."
            echo "- Please check the GitHub Settings or contact repository administrators."
            exit 1
          fi
          
          # retrict update the PAT token
          if [ "$INPUT_NAME" = "PAT_SECRETS_MANAGER" -o "$GH_TOKEN" = "" -o "$GH_TOKEN" = "null" -o "$GH_TOKEN" = "none" ]; then
            echo "❌ ERROR: You could not update this managed secret '$INPUT_NAME'"
            exit 1
          fi
          echo "✅ Authenticated! Permissions had been grant!"
      
      # Check secret existing and update
      - name: ⚙️ Check and Update Secret
        if: success()                 # if previous step is successful
        env:
          # Use secret PAT to grant permission to update secrets instead of using default GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.PAT_SECRETS_MANAGER }}
          INPUT_NAME: ${{ github.event.inputs.secret_name }}
          INPUT_VALUE: ${{ github.event.inputs.secret_value }}
        run: |
          # request present secrets list, find by secret name to update
          echo "🛡️ Checking Secret: $INPUT_NAME..."
          SECRET_EXISTS=$(gh secret list --repo ${{ github.repository }} | awk '{print $1}' | grep -Fx "$INPUT_NAME" || true)
          
          if [ -n "$SECRET_EXISTS" ]; then
            echo "✅ SUCCESS: Found Secret '$INPUT_NAME'. Updating new value..."
            echo "$INPUT_VALUE" | gh secret set "$INPUT_NAME" --repo ${{ github.repository }}
            echo "✅ Updated Secret '$INPUT_NAME' successful."
          else
            echo "❌ ERROR: Not found any Secret by name '$INPUT_NAME' to update!"
            exit 1
          fi

