name: 🗑️ Clean up workflows history / logs

on:
  # manual trigger workflow
  workflow_dispatch:
    
  # allow other workflow call into (inputs same as workflow_dispatch but required)
  workflow_call:
    
  schedule:
    - cron: "0 0 * * 0" # every Sunday at 0:00

# permissions for GitHub Actions READ/WRITE
permissions:
  contents: read
  actions: write

# enviroment
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

jobs:
  # ==============================================================================
  # 🗑️ Clear history / logs
  # ==============================================================================
  clear-history:
    name: 🗑️ Clean up workflows history / logs
    runs-on: ubuntu-latest
    steps:
      # Check whether allow for running workflow
      - name: 🛡️ Gatekeeper - Validate Administrative Access
        env:
          ALLOW_CLEANUP_HISTORY: ${{ secrets.ALLOW_CLEANUP_HISTORY }}
        if: ${{ env.ALLOW_CLEANUP_HISTORY != 'true' }}
        run: |
          echo "❌ Deployment is administratively DISABLED via GitHub Secrets (secrets.ALLOW_CLEANUP_HISTORY is not true)."
          echo "Terminating pipeline execution immediately to protect production infrastructure."
          exit 1 # Require Admin Rights
      
      # clean up history / logs
      - name: Clear workflows history / logs
        if: success()                 # if previous step is successful
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1          # keep 1 day (clean all history)
          keep_minimum_runs: 1    # keep at least one latest run to avoid system error
          use_daily_retention: true     # Changes the minimum run count from overall to per-day

