name: ⚠️ [ GitHub Security ] Export All GitHub Secrets CI/CD Pipeline

on:
  # manual trigger workflow
  workflow_dispatch:
  

# enviroment
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  LANG: 'C.UTF-8'
  LC_ALL: 'C.UTF-8'

jobs:
  # ==============================================================================
  # ⚡ Dump GitHub Secrets
  # ==============================================================================
  export:
    name: ⚡ Dump GitHub Secrets
    runs-on: ubuntu-latest
    steps:
      # Check whether allow for running workflow
      - name: 🔐 Gatekeeper - Validate Administrative Access
        env:
          ALLOW_EXPORT_SECRETS: ${{ secrets.ALLOW_EXPORT_SECRETS }}
        if: ${{ env.ALLOW_EXPORT_SECRETS != 'true' }}
        run: |
          echo "❌ Deployment is administratively DISABLED via GitHub Secrets (secrets.ALLOW_EXPORT_SECRETS is not true)."
          echo "Terminating pipeline execution immediately to protect production infrastructure."
          exit 1 # Require Admin Rights
      
      # Check whether manager token permissions
      - name: 🛡️ Gatekeeper - Validate Manager Token Access
        if: success()                 # if previous step is successful
        env:
          # Use secret PAT to grant permission to update secrets instead of using default GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.PAT_SECRETS_MANAGER }}
        run: |
          echo "🛡️ Checking permissions to update..."
          if ! gh auth status > /dev/null 2>&1; then
            echo "❌ CRITICAL ERROR: Token 'PAT_SECRETS_MANAGER' is INVALID / EXPIRED / NOT EXISTED."
            echo "- Please check the GitHub Settings or contact repository administrators."
            exit 1
          fi
          echo "✅ Authenticated! Permissions had been grant!"
      
      # Dump secrets
      - name: 💾 Dump and Encode Secrets
        if: success()                 # if previous step is successful
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          set -eo pipefail
          echo "Whole GitHub Secrets (base64):"
          echo "$SECRETS_CONTEXT" | jq 'del(.github_token, .PAT_SECRETS_MANAGER)' | base64 -w 0
          echo ""
          echo "$SECRETS_CONTEXT" > decrypted_secrets.json
      
      # Upload to artifact for downloading
      - name: 📤 Upload Descrypted Secrets Artifact for Download
        if: success()                 # if previous step is successful
        uses: actions/upload-artifact@v4
        with:
          name: github-repository-secrets
          path: decrypted_secrets.json
          retention-days: 1     # auto delete file on GitHub after 1 days to save resources
      
      # Inject Artifact Download Link Into Job Run Summary
      - name: 📊 Inject Descrypted Secrets Artifact Download Link Into Job Run Summary
        if: success()                               # if previous step is successful
        run: |
          echo "📚 Compiling Markdown interface parameters for Github Steps Summary..."
          
          # 🎯 GitHub compile link automatically:
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          ARTIFACT_URL="$RUN_URL#artifacts"
          
          # 🏁 Print out to GITHUB_STEP_SUMMARY
          echo "### 📱 Dump descrypted GitHub Secrets Json File" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Descrypted Json File | Download Link |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          
          # Use Markdown [Text](URL) for downloading APK
          echo "| 📦 **Descrypted Secrets Json File** | \`${{ github.sha }}\` | [📥 Download Json File]($ARTIFACT_URL) |" >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "💡 *Note: Artifact preservation lifecycle is locked to exactly 1 days before automated eviction.*" >> $GITHUB_STEP_SUMMARY
          echo "========================================================================="
          echo "✅ Job Summary visualization completed successfully!"
          echo "========================================================================="

